### ISSUE TITLE
求救：CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by Mictorinox** [InternLM/tutorial#2462]
# CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling \`cublasCreate(handle)\`

在尝试运行L1的RAG关卡baseline代码时报错CUBLAS_STATUS_NOT_INITIALIZED

这是尝试运行的代码llamaindex_internlm.py：
```python
from llama_index.llms.huggingface import HuggingFaceLLM
from llama_index.core.llms import ChatMessage
llm = HuggingFaceLLM(
    model_name="/root/model/internlm2-chat-1_8b",
    tokenizer_name="/root/model/internlm2-chat-1_8b",
    model_kwargs={"trust_remote_code":True},
    tokenizer_kwargs={"trust_remote_code":True}
)

rsp = llm.chat(messages=[ChatMessage(content="xtuner是什么？")])
print(rsp)
```

以下是报错信息：
```
Exception has occurred: RuntimeError
CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
  File "/root/.cache/huggingface/modules/transformers_modules/internlm2-chat-1_8b/modeling_internlm2.py", line 344, in forward
    qkv_states = self.wqkv(hidden_states)
  File "/root/.cache/huggingface/modules/transformers_modules/internlm2-chat-1_8b/modeling_internlm2.py", line 639, in forward
    hidden_states, self_attn_weights, present_key_value = self.attention(
  File "/root/.cache/huggingface/modules/transformers_modules/internlm2-chat-1_8b/modeling_internlm2.py", line 932, in forward
    layer_outputs = decoder_layer(
  File "/root/.cache/huggingface/modules/transformers_modules/internlm2-chat-1_8b/modeling_internlm2.py", line 1047, in forward
    outputs = self.model(
  File "/root/Arthur-L1/llamaindex-demo/llamaindex_internlm.py", line 10, in <module>
    rsp = llm.chat(messages=[ChatMessage(content="xtuner是什么？")])
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```
debugger定位到了.cache/huggingface/modules/transformers_modules/internlm2-chat-1_8b/modeling_internlm2.py
![image](https://github.com/user-attachments/assets/ec03b2b4-8c70-4c7a-8090-10ccdaddefdc)

我查了一下，排除的可能原因如下：
1. CUDA内存溢出，应该不是这种情况，因为开发机资源监控显示显存占用8/24G
2. tokenizer和language model不匹配，baseline代码是匹配的
3. 维度存在不一致，base model是稳定发布的版本，应该不存在这个问题

不能确认的可能原因：
1. cuda版本问题，我在开发机输入`nvcc -V`时，显示`nvcc: command not found`，会不会是cuda驱动没有正确安装？

有其他朋友遇到这个报错吗？

**Comment by Mictorinox** [comment]
已解决，导致error的原因是配置环境的时候安装 LLamaIndex 会卸载 torch=2.0.1 并重新安装最新版（ torch=2.5.1），解决办法是重新安装指定版本的 pytorch。

```
conda install --force-reinstall pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
```
感谢@huangjinyuu 同学提出的issue #2264

**Comment by Mictorinox** [comment]
Issue closed.
